# Generated by Django 3.0.3 on 2020-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfinance',
            name='asset_liability_ratio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stockfinance',
            name='base_profit_pre_shares',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stockfinance',
            name='income_pre_shares',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stockfinance',
            name='net_assets_pre_shares',
            field=models.TextField(null=True),
        ),
    ]
